### ISSUE TITLE
toggle_floating not working

### ISSUE THREAD

**Issue by nikotidar** [aesophor/wmderland#24]
Hi again! :dancer: 
I'm trying to use Wmderland on Kali Linux, it's works perfectly! But, toggle_floating is not working. Here's the log (maybe)
```sh
Nov 27 05:26:41 MacBook-Pro kernel: [41269.431278] traps: Wmderland[256837] trap divide error ip:56531cf4db41 sp:7fff96e586e0 error:0 in Wmderland[56531cf4a000+b000]
```
---
Os: Kali 2019.4
Wmderland Build: Latest

**Comment by aesophor** [comment]
Hi there!

I've tried running Wmderland on Kali 2019.4 and floating seems to be working for me.
![](https://i.imgur.com/NfejGv0.png)

May I ask how you started the wm? Did you start it via lightdm, or simply via `startx`?
I started it with `startx`.

**Comment by nikotidar** [comment]
> Hi there!
> 
> I've tried running Wmderland on Kali 2019.4 and floating seems to be working for me.
> ![](https://camo.githubusercontent.com/ef8748fe7569f54f81d32e9d1c907e0cd0606c2b/68747470733a2f2f692e696d6775722e636f6d2f4e66656a4776302e706e67)
> 
> May I ask how you started the wm? Did you start it via lightdm, or simply via `startx`?
> I started it with `startx`.

Hi, Marco!

For login manager, i'm using GDM3.
Thanks before.

**Comment by aesophor** [comment]
I've successfully reproduced the bug by these steps:
1. spawn a window
2. press Mod+g (or Mod+v) multiple times
3. press toggle_floating

The problem is in `Workspace::SetTilingDirection`, setting tiling direction multiple times will mess up the internal data structures. I'll try to redesign the algorithm here. Thanks!

---

I tried running `grep -r ' / '` to find all statements that could potentially lead to divide-by-zero errors:
```
int child_width = (dir == TilingDirection::HORIZONTAL) ? w / children.size() : w;
int child_height = (dir == TilingDirection::VERTICAL) ? h / children.size() : h;
```

**Comment by nikotidar** [comment]
I'm looking for the next update.
Thanks, Marco!

**Comment by aesophor** [comment]
Hello friend,
I've fixed this bug in PR #28 , could you please check if it works on your machine?

Thanks! :smile:

**Comment by nikotidar** [comment]
```toggle_floating``` still not working with ```gdm3``` and ```Wmderland``` latest build, i'm back using ```xinit``` (again) :joy:
